### ISSUE TITLE
[1.19.2] missing mixin properties

### ISSUE THREAD

**Issue by ColonelGerdauf** [gisellevonbingen/Minecraft-GridCraftingMonitor#1]
`[main/ERROR] [mixin/]: Mixin config rs_cmig.mixin.common.json does not specify "minVersion" property`
`[main/ERROR] [mixin/]: Mixin config rs_cmig.mixin.client.json does not specify "minVersion" property`

These errors are spamming the logs, and can mislead users trying to troubleshoot actual issues.

**Comment by gisellevonbingen** [comment]
Good point.
Added minVersion property to all of versions.
It will be applied next version.
